version: '3.8'

services:
  web:
    build: .
#    platform: linux/amd64
    ports:
      - "50000:5000"
    environment:
      - DB_NAME=vulnerable_bank
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db 
      - DB_PORT=5432
